config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"
  get "/settings", to: "pages#settings", as: "settings"

  get "/messages", to: "messages#index", as: "messages"
  post "/messages", to: "messages#create"
  get "/messages/nuke", to: "messages#nuke", as: "messages_nuke"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!
    def index
    end
    
    def create
        @message = current_user.messages.create(message_params)
        if @message.errors.any?
            render plain: "error"
        else
            redirect_to root_path
        end
    end

    def new
    
    end

    def nuke
        Message.delete_all
        redirect_to root_path
    end

    private

    def message_params
        return params.require(:message).permit(:message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @message = Message.new
        @messages = Message.all
        @users = User.all
    end

    def settings
        render plain: "woek"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleDiscordClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'p5.js', media: 'all', 'data-turbolinks-track': 'reload'%>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="grid">
    <div class="grid-item item1">
    </div>
    <div class="grid-item item2">
        <div class="channel-nav-flex">
            <div id="p5-canvas-holder"></div>
            <div class="user-controls-flex">
                <div class="user-image">
                    <%= image_tag "default_image.png", alt: "profile image", class: "profile-image" %>
                </div>
                <div class="user-tag">
                    <%= current_user.email.split("@")[0] %>
                    <br>
                    #1337
                </div>
                <div class="user-settings">
                    <%= button_to "settings", settings_path, method: "get", class: "settings-button" %>
                </div>
                <div class="user-logout">
                    <%= button_to "logout", destroy_user_session_path, method: "delete", class: "logout-button" %>
                </div>
            </div>
        </div>
    </div>
    <div class="grid-item item3">
        <div class="message-area-grid">
            <div class="message-area-item item1">
                <div>
                    <p>Very lonely server</p>
                </div>
                
                <div>
                    <%= button_to "NUKE", messages_nuke_path, method: "get", class: "destroy-button" %>
                </div>
            </div>
            <div class="message-area-item item2">
                <% for message in @messages %>
                    <div class="message-grid">
                        <div class="message-grid-item image">
                            <%= image_tag "default_image.png", alt: "profile image", class: "profile-image" %>
                        </div>
                        <div class="message-grid-item-flex">
                            <div class="flex-item name">
                                <%= message.user.email.split("@").first %>
                            </div>
                            <div class="flex-item message">
                                <%= message.message %>
                            </div>
                        </div>
                        <div class="message-grid-item date">
                            <%= message.created_at %>
                        </div>
                    </div>

                    <% if message.message.match(/(https?:\/\/.*\.(?:png|jpg|gif))/i) %>
                        <div class="message-image">
                            <%= image_tag message.message[/(https?:\/\/.*\.(?:png|jpg|gif))/i, 0], alt: "image", class: "message-media" %>
                        </div>
                    <% end %>
                <% end %>
            </div>
            <div class="message-area-item item3">
                <%= form_with model: @message, local: true, html: { autocomplete: "off" } do |form| %>
                    <%= form.text_field :message, placeholder: "type a message here", class: "text-field-box" %>
                <% end %>
            </div>
        </div>
    </div>
    <div class="grid-item item4">
        <div class="user-list-flex">
            <p style="color: #FFFFFF;">MEMBERS - <%= @users.count %></p>
            <% for user in @users %>
                <div class="user-list-item">
                    <div class="user-image">
                        <%= image_tag "default_image.png", alt: "profile image", class: "profile-image" %>
                    </div>

                    <div class="user-tag">
                        <%= user.email.split("@")[0] %>#1337
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>